[package]
name = "phint"
version = "0.1.0"
authors = ["Jakob Stigloher <pixunil@gmx.de>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
gtk = {version = "0.1.3", features = ["v3_10"]}
cairo-rs = "0.1.3"
